spring:

  mvc:
    view:
      prefix: /views/
      suffix: .jsp

  datasource:
    read:
      jdbc-url: jdbc:sqlserver://120.79.38.192:1433;databasename=ycreal
      password: Mjf19921030
      username: sa
    read2:
      jdbc-url: jdbc:sqlserver://120.79.38.192:1433;databasename=ycreal
      password: Mjf19921030
      username: sa
    write:
      jdbc-url: jdbc:sqlserver://120.79.38.192:1433;databasename=my_forecast
      password: Mjf19921030
      username: sa