spring:

  mvc:
    view:
      prefix: /views/
      suffix: .jsp

  datasource:
    read:
      jdbc-url: jdbc:sqlserver://10.36.162.18:1433;databasename=ycreal_all
      password: gzsw_1220
      username: gzsw
    read2:
      jdbc-url: jdbc:sqlserver://10.36.162.20:1433;databasename=rwdb
      password: gzsw_1220
      username: gzsw
    write:
      jdbc-url: jdbc:sqlserver://10.36.162.20:1433;databasename=my_forecast
      password: gzsw_1220
      username: gzsw