logging:
  level:
     gz.sw.mapper.write : debug

spring:

  mvc:
    view:
      prefix: /views/
      suffix: .jsp

  datasource:
#    read:
#      jdbc-url: jdbc:sqlserver://120.79.38.192:1433;databasename=ycreal
#      password: Mjf19921030
#      username: sa
#    read2:
#      jdbc-url: jdbc:sqlserver://120.79.38.192:1433;databasename=ycreal
#      password: Mjf19921030
#      username: sa
#    write:
#      jdbc-url: jdbc:sqlserver://120.79.38.192:1433;databasename=my_forecast
#      password: Mjf19921030
#      username: sa
    read:
#      jdbc-url: jdbc:sqlserver://127.0.0.1:1433;databasename=rwdb
#      password: xss@8113234
#      username: sa
      jdbc-url: jdbc:sqlserver://10.36.162.3:1433;databasename=ycreal_all
      password: gzsw_1220
      username: gzsw
    read3:
      jdbc-url: jdbc:sqlserver://127.0.0.1:1433;databasename=rwdb
      password: xss@8113234
      username: sa
    read2:
      jdbc-url: jdbc:sqlserver://127.0.0.1:1433;databasename=rdwd20
      password: xss@8113234
      username: sa
    write:
      jdbc-url: jdbc:sqlserver://127.0.0.1:1433;databasename=my_forecast
      password: xss@8113234
      username: sa